## Default profile
spring:
  application:
    name: OhMyFamily
  profiles:
    active: dev
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    displayRequestDuration: true
---
# h2
#spring:
#  h2:
#    console:
#      enabled: true
#      path: ${H2_PATH}
#      settings:
#        web-allow-others: true
#  datasource:
#    url: ${H2_URL}
#    driver-class-name: org.h2.Driver
#    username: ${H2_USERNAME}
#    password: ${H2_PASSWORD}
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create

spring:
  profiles:
    active: local
  session:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost:3306/OMF
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

---
#jwt
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: ${JWT_ACCESS_TOKEN_TIME}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_TIME}

---
#kakao
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com

---
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

---
cloud:
  aws:
    s3:
      bucket: oh-my-family-bucket
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${REGION}
    stack:
      auto: false
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB